version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  # Optional: Add PostgreSQL database
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: it_support
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
