# Development override - use this for local development
version: '3.8'

services:
  backend:
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - RELOAD=true
    command: ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000

  nginx:
    ports:
      - "8080:80"
